layout_spectrum: 0.20458809839432487
typography_spectrum: 0.18284017009503845
color:
  brandStrength: 0.5144056276149938
  lightness: 0.9535811720996873
  saturation: 0.07077407876269358
  rhythmicContrast: 0.34430138754003714
  brandColors:
    - '#F4F2ED'
    - '#FBF9F1'
    - '#FDFDF9'
    - '#F0ECE8'
    - '#FFFFFF'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/69c3b18b-99c5-4132-bfaf-d7831345aedd.png
name: abc.. to xyz
url: 'http://thegrid.ai/abcxyz'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: adding forms
    url: 'http://forms.abc-xyz.us'
    type: external
  - name: adding video
    url: 'http://video.abc-xyz.us'
    type: external
  - name: add a store
    url: 'http://store.abc-xyz.us'
    type: external
  - name: more..
    id: 108e8747-58b3-425b-ae60-70443634ce6a
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/14d2909f-e808-443e-a2ce-86db1fd74fa9.png
title: abc.. to xyz
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7edd258b-b4f7-4a2a-882b-13f4dd2a4b65.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7edd258b-b4f7-4a2a-882b-13f4dd2a4b65.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: creating your site on thegrid.io
purpose:
  - type: internal
    label: contact us
    item: 419e3737-aa21-4d90-b247-3b9ef3f700a7
analytics:
  google: UA-105750982-1
  twitter: '#abc..toxyz'
