typography_spectrum: 0.18029237413695912
color:
  brandStrength: 0.48076718655839046
  lightness: 0.9577909018042138
  saturation: 0.07283206893490757
  rhythmicContrast: 0.34488601718328454
  brandColors:
    - '#F4F2ED'
    - '#FBF9F1'
    - '#FDFDF9'
    - '#F0ECE8'
    - '#FFFFFF'
github: true
layout_spectrum: 0.03631039887712807
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/df5fc339-7084-41b4-9195-f4f227e78f2a.png
name: abc.. to xyz
url: 'http://abc-xyz.us'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: adding forms
    url: 'http://forms.abc-xyz.us'
    type: external
  - name: adding video
    url: 'http://video.abc-xyz.us'
    type: external
  - name: add a store
    url: 'http://store.abc-xyz.us'
    type: external
  - name: more..
    id: 108e8747-58b3-425b-ae60-70443634ce6a
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/14d2909f-e808-443e-a2ce-86db1fd74fa9.png
title: abc.. to xyz
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7edd258b-b4f7-4a2a-882b-13f4dd2a4b65.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7edd258b-b4f7-4a2a-882b-13f4dd2a4b65.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: creating your grid site..
